case_style = "SnakeCase" #[SnakeCase, CamelCase, PascalCase, ScreamingSnakeCase, Raw]

[types]
prefix = "EzFfi"
case_style = "PascalCase"

[fns]
prefix = ""
suffix = ""

[free_fns]
prefix = ""
suffix = ""
